udp_bridge/maxPacketSize: 1400
udp_bridge/remotes:
    operator:
        host: 192.168.100.199
        port: 4201
        topics:
          sensors_flir_engine: {source: sensors/flir_engine}
          sensors_ais_contact: {source: sensors/ais/contact}
          mbr_9372_2510_margin_avg: {source: mbr/9372/2510/margin_avg}
          mbr_9372_2510_margin_min: {source: mbr/9372/2510/margin_min}
          sensors_radar_HaloA_data: {source: sensors/radar/HaloA/data}
          sensors_radar_HaloA_state: {source: sensors/radar/HaloA/state}
          sensors_radar_HaloB_data: {source: sensors/radar/HaloB/data}
          sensors_radar_HaloB_state: {source: sensors/radar/HaloB/state}
          mobile_position: {source: /mobile/base/position, destination: /operator/base/position}
    observer:
        topics:
          sensors_ais_contact: {source: sensors/ais/contact}

mbr_node/radioSerialNumbers: [2510, 9442]

sonar/model: 2040
sonar/host: stormi
