udp_bridge/remotes/robot/name: echo

project11/platforms/echo:
  robot_description: ben/robot_description
  width: 1
  length: 1.5
  reference_x: 0.525
  nav_sources:
    combined:
      position_topic: /echo/project11/nav/position
      orientation_topic: /echo/project11/nav/orientation
      velocity_topic: /echo/project11/nav/velocity
