udp_bridge/remotes:
    robot:
        name: echo
        host: 10.42.0.10
        port: 4200
        topics:
          position_topic: /echo/project11/nav/position
          orientation_topic: /echo/project11/nav/orientation
          velocity_topic: /echo/project11/nav/velocity
